config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/devise/sessions'
  }

  devise_for :users, controllers: {
         sessions: 'users/devise/sessions',
    registrations: 'users/devise/registrations',
      invitations: 'users/devise/invitations',
        passwords: 'users/devise/passwords',
    confirmations: 'users/devise/confirmations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :users do
    resources :home, only: :index
    resources :contests
    resources :payments
    resources :member_contests, only: :show
  end

  namespace :admins do
    resources :homes
    resources :list_contests do
      collection do
        get :list_wira
      end
    end
    resources :payments, only: %i[index show] do
      member do
        put :accept
        put :reject
      end
    end
    resources :notifications, only: %i[index show] do
      collection do
        get :all_notification_read
      end
    end
    resources :users, only: %i[index show]
    root 'homes#index'
  end

  resources :homes

  root 'homes#index'
end

app/models/list_contest.rb
class ListContest < ApplicationRecord
  enum type_pmr: [:madya, :wira]
  enum type_contest: [
                      :first_aid, :family_care, :stretcher,
                      :asincan, :doras, :rsps, :leadership,
                      :history
                    ]

  has_one  :inventory, as: :inventoryable
  has_many :member_contests
  has_many :value_formats

  before_destroy :check_member_contests

  serialize :value_format, Hash

  scope :get_list_contests, ->(type_pmr) { where(type_pmr: type_pmr) }

  accepts_nested_attributes_for :inventory

  def check_member_contests
    return if member_contests.blank?

    self.errors.add(:base, "Mata lomba tidak bisa dihapus karena ada peserta yang daftar!")
    throw(:abort)
  end

  class << self
    def title_names
      {
        first_aid: 'Pertolongan Pertama', family_care: 'Perawatan Keluarga',
        stretcher: 'Tandu Darurat', asincan: 'Ayo Siaga Bencana',
        doras: 'Donor Darah Sukarela', rsps: 'Remaja Sehat Peduli Sesama',
        leadership: 'Kepemimpinan', history: 'Gerakan'
      }
    end

    def get_member_contest(type_pmr)
      get_list_contests = get_list_contests(type_pmr)
      hash_member_contests = {}

      get_list_contests.each do |list_contest|
        type_contest = list_contest.type_contest
        hash_member_contests[type_contest.to_sym] = list_contest.member_contests.count
      end

      hash_member_contests
    end
  end
end

app/controllers/admins/list_contests_controller.rb
class Admins::ListContestsController < Admins::AdminBaseController
  include Modules::Crudable

  before_action :set_member_contest, only: :show
  before_action :form_collection, only: %i[new create edit update]
  before_action :to_integer_price_update, only: %i[update]
  before_action :to_integer_price_create, only: %i[create]
  before_action :set_redirect_path, only: %i[create update destroy]

  self.additional_parameters = [
    inventory_attributes: %i[_destroy id stock price inventoryable_id inventoryable_type]
  ]

  def index
    super do
      @list_contests = ListContest.get_list_contests('madya')
      @name_page = 'Madya'
    end
  end

  def list_wira
    @list_contests = ListContest.get_list_contests('wira')
    @name_page = 'Wira'
  end

  def new
    super do
      @list_contest.build_inventory
    end
  end

  private

  def set_member_contest
    @member_contests = @list_contest.member_contests
  end

  def form_collection
    @type_pmrs     = ListContest::type_pmrs.map { |key, value| [key.titleize, key] }
    @type_contests = ListContest::type_contests.map { |key, value| [ListContest.title_names[key.to_sym], key] }
  end

  def to_integer_price_update
    params[:list_contest][:inventory_attributes][:price] = format_rupiah_price
  end

  def to_integer_price_create
    resource.inventory.price = format_rupiah_price
  end

  def format_rupiah_price
    format_price = params[:list_contest][:inventory_attributes][:price].delete('Rp.').strip.to_i
  end

  def set_redirect_path
    set_redirect = if resource.type_pmr.eql?('wira')
                    list_wira_admins_list_contests_path
                   else
                    admins_list_contests_path
                   end
    self.redirect_path = set_redirect
  end
end

app/views/admins/list_contests/partials/_form.html.erb
<% if list_contest.errors.present? %>
  <div class="row purchace-popup">
    <div class="col-12 stretch-card grid-margin">
      <div class="card card-secondary">
        <span class="card-body align-items-center">
          <h4 class="mb-lg-0">Error Message!</h4>
          <ul>
            <% list_contest.errors.full_messages.each do |key| %>
            <li><%= key %></li>
            <% end %>
          </ul>
        </span>
      </div>
    </div>
  </div>
<% end %>

<%= form_with(model: list_contest, url: url, local: true, class: "forms-sample") do |f| %>
  <% params_action_edit = ['update', 'edit'].include?params[:action] %>
  <div id="action_edit" data-action-edit="<%= params_action_edit %>"></div>
  <div class="form-group">
    <%= f.label :title, 'Mata Lomba' %>
    <%= f.text_field :title, class: 'form-control', placeholder: 'Mata Lomba', required: true, id: 'title_contest' %>
  </div>
  <div class="form-group">
    <%= f.label :type_pmr, 'Type PMR' %>
    <%= f.select :type_pmr,
        options_for_select(type_pmrs, list_contest.type_pmr),
        { include_blank: 'Select Type PMR' }, class: 'form-control', required: true, disabled: params_action_edit, id: 'type_pmrs' %>
  </div>
  <div class="form-group">
    <%= f.label :type_contest, 'Kategori Mata Lomba' %>
    <%= f.select :type_contest,
        options_for_select(type_contests, list_contest.type_contest),
        { include_blank: 'Select Kategori Mata Lomba' }, class: 'form-control', required: true, disabled: params_action_edit %>
  </div>

  <div class="form-group">
    <% title1 = 'Code PMR default didapat dari title dan type pmr, contoh PPW(Pertolongan Pertama Wira) dan bisa di edit' %>
    <% title2 = 'Code PMR tidak bisa di edit! hanya bisa di edit ketika membuat mata lomba baru!' %>
    <%= f.label :code, params_action_edit ? title2 : title1 %>
    <%= f.text_field :code, class: 'form-control', required: true, id: 'code_pmr', placeholder: 'PPW', disabled: params_action_edit %>
  </div>

  <%= f.fields_for :inventory do |ff| %>
    <div class="form-group">
      <%= ff.label :stock, 'Kuota' %>
      <%= ff.number_field :stock, class: 'form-control', min: 1, placeholder: 1, required: true %>
    </div>

    <div class="form-group">
      <%= ff.label :price, 'Harga' %>
      <%= ff.text_field :price, value: ff.object.price, class: 'form-control', id: 'format_rupiah', placeholder: 'Harga', required: true %>
    </div>
  <% end %>

  <%= f.submit text_submit, class: 'btn btn-primary mr-2' %>
  <%= link_to 'Cancel', admins_list_contests_path, class: 'btn btn-light' %>
<% end %>


<script>
  $('#format_rupiah').val(formatRupiah($('#format_rupiah').val(), 'Rp. '))
  $('#format_rupiah').keyup(function() {
    var format_rupiah = formatRupiah($(this).val(), 'Rp. ')
    console.log(format_rupiah)

    $(this).val(format_rupiah)
  })

  $('#title_contest').keyup(function() {
    $(this).val($(this).val().toUpperCase())
    getCodePMR()
  })

  $('#type_pmrs').change(function() {
    getCodePMR()
  })

  function formatRupiah(angka, prefix){
    var number_string = angka.replace(/[^,\d]/g, '').toString(),
    split       = number_string.split(','),
    sisa        = split[0].length % 3,
    rupiah        = split[0].substr(0, sisa),
    ribuan        = split[0].substr(sisa).match(/\d{3}/gi);
   
    // tambahkan titik jika yang di input sudah menjadi angka ribuan
    if(ribuan){
      separator = sisa ? '.' : '';
      rupiah += separator + ribuan.join('.');
    }
   
    rupiah = split[1] != undefined ? rupiah + ',' + split[1] : rupiah;
    return prefix == undefined ? rupiah : (rupiah ? 'Rp. ' + rupiah : '');
  }

  function getCodePMR() {
    var params_action_edit = $('#action_edit').data('action-edit');
    if (!params_action_edit) {
      var title_contest = $('#title_contest').val().split(' ');
      var arr_title = [];
      if (!!title_contest) {
        $.each(title_contest, function(idx, title) {
          arr_title.push(title.split('')[0])
        })
        var type_pmr = $('#type_pmrs').val().split('')[0]
        if (!!type_pmr) {
          arr_title.push(type_pmr.toUpperCase())
        }
        $('#code_pmr').val(arr_title.join(''))
      }
    }
  }
</script>

app/views/admins/list_contests/partials/_list_contests.html.erb
<div class="card-body">
  <h4 class="card-title">List Mata Lomba <%= name_page %></h4>
  <%= link_to 'MADYA', admins_list_contests_path, class: 'btn btn-primary' %>
  <%= link_to 'WIRA', list_wira_admins_list_contests_path, class: 'btn btn-warning' %>
  <%= link_to 'Tambah Mata Lomba', new_admins_list_contest_path, class: 'btn btn-success' %>
  <div class="table-responsive border rounded p-1">
    <table class="table">
      <thead>
        <tr>
          <th class="font-weight-bold">No</th>
          <th class="font-weight-bold">Mata Lomba</th>
          <th class="font-weight-bold">Type PMR</th>
          <th class="font-weight-bold">Code PMR</th>
          <th class="font-weight-bold">Kuota</th>
          <th class="font-weight-bold">Harga</th>
          <th></th>
        </tr>
      </thead>
      <%= no_table_record(list_contests, '7') %>
      <tbody>
        <% list_contests.each_with_index do |list_contest, idx| %>
          <% inventory = list_contest.inventory %>
          <tr>
            <td><%= idx + 1 %></td>
            <td><%= list_contest.title %></td>
            <td><%= list_contest.type_pmr.titleize %></td>
            <td><%= list_contest.code %></td>
            <td><%= inventory.stock %></td>
            <td><%= number_to_currency(inventory.price, unit: 'Rp. ', separator: ".", precision: 0) %></td>
            <td>
              <%= link_to 'Show', admins_list_contest_path(list_contest), class: 'btn btn-primary btn-sm' %>
              <%= link_to 'Edit', edit_admins_list_contest_path(list_contest), class: 'btn btn-warning btn-sm' %>
              <%= link_to 'Delete', admins_list_contest_path(list_contest), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="d-flex mt-4 flex-wrap">
    <p class="text-muted">Showing 1 to 10 of 57 entries</p>
    <nav class="ml-auto">
      <ul class="pagination separated pagination-info">
        <li class="page-item"><a href="#" class="page-link"><i class="icon-arrow-left"></i></a></li>
        <li class="page-item active"><a href="#" class="page-link">1</a></li>
        <li class="page-item"><a href="#" class="page-link">2</a></li>
        <li class="page-item"><a href="#" class="page-link">3</a></li>
        <li class="page-item"><a href="#" class="page-link">4</a></li>
        <li class="page-item"><a href="#" class="page-link"><i class="icon-arrow-right"></i></a></li>
      </ul>
    </nav>
  </div>
</div>

app/views/admins/list_contests/partials/_table_member_contest.html.erb
<div class="row">
  <div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Daftar Peserta Lomba</h4>
        <div class="table-responsive border rounded p-1">
          <table class="table">
            <thead>
              <tr>
                <th class="font-weight-bold">No</th>
                <th class="font-weight-bold">School</th>
                <th class="font-weight-bold">Code PMR</th>
                <th class="font-weight-bold">Penolong 1</th>
                <th class="font-weight-bold">Penolong 2</th>
                <th class="font-weight-bold">Penolong 3</th>
              </tr>
            </thead>
            <%= no_table_record(member_contests, '6') %>
            <tbody>
              <% member_contests.each_with_index do |member_contest, idx| %>
                <tr>
                  <td><%= idx + 1 %></td>
                  <td><%= member_contest.school %></td>
                  <td><%= member_contest.code %></td>
                  <td><%= member_contest.helper_1 %></td>
                  <td><%= member_contest.helper_2 %></td>
                  <td><%= member_contest.helper_3 %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="d-flex mt-4 flex-wrap">
          <p class="text-muted">Showing 1 to 10 of 57 entries</p>
          <nav class="ml-auto">
            <ul class="pagination separated pagination-info">
              <li class="page-item"><a href="#" class="page-link"><i class="icon-arrow-left"></i></a></li>
              <li class="page-item active"><a href="#" class="page-link">1</a></li>
              <li class="page-item"><a href="#" class="page-link">2</a></li>
              <li class="page-item"><a href="#" class="page-link">3</a></li>
              <li class="page-item"><a href="#" class="page-link">4</a></li>
              <li class="page-item"><a href="#" class="page-link"><i class="icon-arrow-right"></i></a></li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>