config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/devise/sessions'
  }

  devise_for :users, controllers: {
         sessions: 'users/devise/sessions',
    registrations: 'users/devise/registrations',
      invitations: 'users/devise/invitations',
        passwords: 'users/devise/passwords',
    confirmations: 'users/devise/confirmations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :users do
    resources :home, only: :index
    resources :contests
    resources :payments
    resources :member_contests, only: :show
  end

  namespace :admins do
    resources :homes
    resources :list_contests do
      collection do
        get :list_wira
      end
    end
    resources :payments, only: %i[index show] do
      member do
        put :accept
        put :reject
      end
    end
    resources :notifications, only: %i[index show] do
      collection do
        get :all_notification_read
      end
    end
    resources :users, only: %i[index show]
    root 'homes#index'
  end

  resources :homes

  root 'homes#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  has_one :profile, dependent: :destroy
  has_one :contest, dependent: :destroy
  has_one :order,   dependent: :destroy

  validates :email, uniqueness: true

  accepts_nested_attributes_for :profile, reject_if: :all_blank
  accepts_nested_attributes_for :contest, reject_if: :all_blank
  accepts_nested_attributes_for :order, reject_if: :all_blank
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < Admins::AdminBaseController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @profile = @user.profile
    @member_contests = @user.contest.member_contests
  end
end

app/controllers/users/base_controller.rb
class Users::BaseController < ApplicationController
  before_action :authenticate_user!
  layout 'application_user'

  def current_profile
    current_user.profile
  end

  def current_order
    current_user.order
  end
end

app/controllers/users/contests_controller.rb
class Users::ContestsController < Users::BaseController
  include Modules::Crudable

  self.additional_parameters = [
    member_contests_attributes: %i[id _destroy helper_1 helper_2 helper_3 contest_id list_contest_id school]
  ]

  before_action :set_list_contests, only: :index
  before_action :set_collection, only: %i[new create edit update]
  before_action :set_contest, only: %i[new create edit update]
  before_action :set_redirect_path, only: %i[create update]

  def new
    super do
      @contest.member_contests.new
    end
  end

  def create
    super
  end

  private

  def set_list_contests
    @member_contests = current_user.contest.member_contests.includes(:list_contest).order_desc
  end

  def set_collection
    @list_contests = ListContest.get_list_contests(current_profile.type_pmr)
    @list_contests = build_select_options(@list_contests, { label: %i[title], value: :id })
  end

  def set_contest
    @contest = current_user.contest
  end

  def set_redirect_path
    self.redirect_path = users_contests_path
  end
end

app/controllers/users/home_controller.rb
class Users::HomeController < Users::BaseController
  def index
    
  end

end

app/controllers/users/member_contests_controller.rb
class Users::MemberContestsController < Users::BaseController
  def show
    @member_contest = MemberContest.find(params[:id])
  end
end

app/controllers/users/payments_controller.rb
class Users::PaymentsController < Users::BaseController
  include Modules::Crudable

  self.additional_parameters = [:avatar]

  before_action :authorize_payment
  before_action :set_total_payment_user, only: :index
  before_action :set_remaining_user, only: :index
  before_action :set_redirect_path, only: %i[create new edit update]
  before_action :set_status_payment, only: %i[create new edit update]
  before_action :set_not_confim_payment, only: :index
  before_action :set_total_payments, only: :index
  before_action :calculate_all_payments, only: :index

  def index
    super do
      @payments = current_order.payments.order(created_at: :desc)
    end
  end

  private

  def authorize_payment
    if current_user.contest.member_contests.blank?
      redirect_to users_contests_path, alert: 'Tidak bisa access halaman payment!!'
    end
  end

  def set_total_payment_user
    @total_payment_user = current_order.get_payment_user
  end

  def set_remaining_user
    @remaining_payment_user = current_order.remaining_payment
  end

  def set_redirect_path
    self.redirect_path = users_payments_path
  end

  def set_status_payment
    resource.status = Payment.statuses[:pending]
  end

  def set_not_confim_payment
    @not_confirm_payment = current_order.not_confirm_payments
  end

  def set_total_payments
    @total_payments = current_order.get_total_payment
  end

  def calculate_all_payments
    @calculate_all_payments = current_order.calculate_all_payment
  end
end

app/views/admins/users/index.html.erb
<div class="row">
  <div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">All Users</h4>
        <div class="table-responsive border rounded p-1">
          <table class="table">
            <thead>
              <tr>
                <th class="font-weight-bold">No</th>
                <th class="font-weight-bold">Email</th>
                <th class="font-weight-bold">Name Offical</th>
                <th class="font-weight-bold">Nama School</th>
                <th class="font-weight-bold">Type PMR</th>
                <th></th>
              </tr>
            </thead>
            <%= no_table_record(@users, '6') %>
            <tbody>
              <% @users.each_with_index do |user, idx| %>
                <% profile = user.profile %>
                <tr>
                  <td><%= idx + 1 %></td>
                  <td><%= user.email %></td>
                  <td><%= profile.name %></td>
                  <td><%= profile.school %></td>
                  <td><%= profile.type_pmr.titleize %></td>
                  <td>
                    <%= link_to 'Show', admins_user_path(user), class: 'btn btn-primary btn-sm' %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="d-flex mt-4 flex-wrap">
          <p class="text-muted">Showing 1 to 10 of 57 entries</p>
          <nav class="ml-auto">
            <ul class="pagination separated pagination-info">
              <li class="page-item"><a href="#" class="page-link"><i class="icon-arrow-left"></i></a></li>
              <li class="page-item active"><a href="#" class="page-link">1</a></li>
              <li class="page-item"><a href="#" class="page-link">2</a></li>
              <li class="page-item"><a href="#" class="page-link">3</a></li>
              <li class="page-item"><a href="#" class="page-link">4</a></li>
              <li class="page-item"><a href="#" class="page-link"><i class="icon-arrow-right"></i></a></li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/users/show.html.erb
<div class="row">
  <div class="col-md-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col-md-8">
            <h2>Show User <%= @profile.name %></h2>
          </div>
          <div class="col-md-4 text-right">
            <%= link_to 'Back', admins_users_path, class: 'btn btn-primary btn-sm' %>
          </div>
        </div>
        <div class="mt-2">
          <h4>Email</h4>
          <p class="card-description"><%= @user.email %></p>
        </div>
        <div class="mt-2">
          <h4>Name Official</h4>
          <p class="card-description"><%= @profile.name %></p>
        </div>
        <div class="mt-2">
          <h4>Name School</h4>
          <p class="card-description"><%= @profile.school %></p>
        </div>
        <div class="mt-2">
          <h4>Phone Number</h4>
          <p class="card-description"><%= @profile.phone %></p>
        </div>
        <div class="mt-2">
          <h4>Type PMR</h4>
          <p class="card-description"><%= @profile.type_pmr.titleize %></p>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'admins/list_contests/partials/table_member_contest', locals: { member_contests: @member_contests } %>